version: '3.5'
services:
    mongodb:
        container_name: mongo
        image: mongo:3.6
        ports:
            - 27017:27017
        command: mongod --smallfiles # --quiet
        volumes:
            - /mongodata:/data/db